### ISSUE TITLE
Delta Machine Problem

### ISSUE THREAD

**Issue by hwk1984** [kateliev/TypeRig#54]
```
Traceback (most recent call last):
  File "C:/Users/userXXX/Documents/FontLab/FontLab 7/Scripts/Delta Machine/DeltaMachine.py", line 755, in <module>
    dialog = dlg_DeltaMachine()
  File "C:/Users/userXXX/Documents/FontLab/FontLab 7/Scripts/Delta Machine/DeltaMachine.py", line 331, in __init__
    self.active_font = pFont()
NameError: global name 'pFont' is not defined
```

`app_version = '1.12'
app_name = 'TypeRig | Delta Machine'`

Fontlab version 7.2.0.7649 Win x64

This problem results regardless of whether it is downloaded in the software or manually installed by GitHub download (TypeRig v1.5 EOF Py2.7), pls help, thanks!

**Comment by kateliev** [comment]
Hi @hwk1984 as explained here #56 code changed a bit. Please get the latest version from this repo and try again. To me it seems that most of the users having these problems are using old GUI based scripts with the latest core or vice versa.
