### ISSUE TITLE
Error messages with Delta Machine, TypeRig GUI Manager on FontLab 8, Windows 11 OS

### ISSUE THREAD

**Issue by StefanPeev** [kateliev/TypeRig#85]
### Delta Machine

Traceback (most recent call last):
  File "C:/Users/AcerPC/Documents/FontLab/FontLab 8/Scripts/Delta Machine/DeltaMachine.py", line 28, in <module>
    from typerig.proxy.fl.gui.widgets import getProcessGlyphs, TRSliderCtrl, TRMsgSimple
ImportError: cannot import name 'TRMsgSimple' from 'typerig.proxy.fl.gui.widgets' (C:\Users\AcerPC\Documents\FontLab\FontLab 8\Scripts\Lib\typerig\proxy\fl\gui\widgets.py)

### TypeRig GUI Manager
Traceback (most recent call last):
  File "C:/Users/AcerPC/Documents/FontLab/FontLab 8/Scripts/TypeRig GUI/typerig-manager.py", line 68, in <module>
    dialog = typerig_Manager()
             ^^^^^^^^^^^^^^^^^
  File "C:/Users/AcerPC/Documents/FontLab/FontLab 8/Scripts/TypeRig GUI/typerig-manager.py", line 47, in __init__
    self.tabs.addTab(eval('Manager.%s.tool_tab()' %toolName), toolName)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
  File "C:\Users/AcerPC/Documents/FontLab/FontLab 8/Scripts/TypeRig GUI\Manager\FontMetrics.py", line 309, in __init__
    self.fontMetrics = WFontMetrics(self)
    ^^^^^^^^^^^^^^^^
AttributeError: Slot 'fontMetrics' can not be overwritten on tool_tab object

**Comment by kateliev** [comment]
Здравей Стефане, ще ги погледна тази седмица.

**Comment by kateliev** [comment]
@StefanPeev Здравей отново. Мениджърите са оправени. Поне що касае грешката на този за шрифтовата метрика. Относно проблема с Делта машийн ... за съжаление не мога да потвърдя. При мен тръгва. Може би имаш някаква стара версия която не работи или обуъркване между версиите на ТйапРиг. 

Ако искаш да го оправяме, моля те направи следното: В основната папка на ТайпРиг или тук от репото има файл който се нарича `diag.vfpy`. Пусни си Фонтлаб и завлачи файла вътре сякаш е шрифт (drag+drop) трябва  да се стартира скрипт който излгежка като показания по-долу. Натисни първо на бутона "Get..." и след това на "Save..." и ми изпрати записания JSON файл за сравня с моята исталация. Така ще мога да ти кажа ако някой от ТайпРиг компонените ти е стар и има нужда от преинсталиране...

**Comment by StefanPeev** [comment]
Благодаря, Васко! Прилагам JSON файла.
[TypeRig_SP_01.json](https://github.com/kateliev/TypeRig/files/14044023/TypeRig_SP_01.json)
