### ISSUE TITLE
TypeRig Panel error upon reinstallation

### ISSUE THREAD

**Issue by swanktype** [kateliev/TypeRig#92]
I have been trying to reinstall TypeRig as I wanted to keep it up to date via git. From what I can tell, the core is there, and just about everything works, except for the entire panel. I can get its individual scripts to work, but just not the integrated panel with everything in it. When I try to open the panel it throws the following error:

"
Traceback (most recent call last):
  File "/Users/graemeswank/Documents/TypeRig/Scripts/TypeRig GUI/typerig-panel.py", line 394, in <module>
    dialog = TRMainPanel()
             ^^^^^^^^^^^^^
  File "/Users/graemeswank/Documents/TypeRig/Scripts/TypeRig GUI/typerig-panel.py", line 337, in __init__
    self.options.set_visible_panels()
  File "/Users/graemeswank/Documents/TypeRig/Scripts/TypeRig GUI/typerig-panel.py", line 204, in set_visible_panels
    tab_parent.tabs.addTab(tab_widget.tool_tab(), tab_name)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/graemeswank/Documents/TypeRig/Scripts/TypeRig GUI/Panel/Delta.py", line 626, in __init__
    lay_main.addWidget(TRDeltaPanel())
                       ^^^^^^^^^^^^^^
  File "/Users/graemeswank/Documents/TypeRig/Scripts/TypeRig GUI/Panel/Delta.py", line 91, in __init__
    self.tree_layer.setTree(self.__init_tree(), tree_column_names)
                            ^^^^^^^^^^^^^^^^^^
  File "/Users/graemeswank/Documents/TypeRig/Scripts/TypeRig GUI/Panel/Delta.py", line 274, in __init_tree
    return_data.append((tree_masters_group_name, [(layer, '', '', default_sx, default_sy, eGlyph().layer(layer).wireframeColor) for layer in self.active_font.masters()]))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/graemeswank/Documents/TypeRig/Scripts/TypeRig GUI/Panel/Delta.py", line 274, in <listcomp>
    return_data.append((tree_masters_group_name, [(layer, '', '', default_sx, default_sy, eGlyph().layer(layer).wireframeColor) for layer in self.active_font.masters()]))
                                                                                          ^^^^^^^^
  File "/Users/graemeswank/Library/Application Support/FontLab/FontLab 8/python/3.11/site-packages/typerig/proxy/fl/objects/glyph.py", line 66, in __init__
    self.fl = fl6.flGlyph(fl6.CurrentGlyph(), fl6.CurrentFont())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fgGlyph expected

"

**Comment by swanktype** [comment]
I think I may have not been clicking on the correct TypeRig Panel option.
